### ISSUE TITLE
Return query objects

### ISSUE THREAD

**Issue by joshuabaker** [objectivehtml/Channel-Data#6]
At present I’m trying to achieve a where_in without using a load of OR statements. Perhaps this is possible and I’m just not aware of it.

It would be great to be able to get a query object for methods (f.ex. `get_channel_entries_query`) so we can adjust the SQL prior to firing the get.

Do you have any thoughts or see any issue with something like that?

**Comment by objectivehtml** [comment]
I see your point, but in this case, I don't think you need to go that far. You can pretty much build any conditional with Channel Data now. Be sure to use the dev branch, it has way more features for conditionals.

You can do this:

```
$this->EE->channel_data->get_channel_entries(1, array(
    'where' => array(
        'exp_channel_titles.entry_id' => array('OR 1', 'OR 2', 'OR 3', 'OR 4')
    )
));
```

That will produce the following SQL:

SELECT exp_channel_data.entry_id, exp_channel_data.channel_id, exp_channel_titles.author_id, exp_channel_titles.title, exp_channel_titles.url_title, exp_channel_titles.entry_date, exp_channel_titles.expiration_date, status, exp_channel_titles.`entry_id`, exp_channel_titles.`channel_id`, exp_channel_titles.`title`, exp_channel_titles.`author_id`, exp_channel_titles.`entry_date`, exp_channel_titles.`expiration_date`, exp_channel_titles.`status`, exp_channel_data.`field_id_8` as 'page_description', exp_channel_data.`field_id_3` as 'page_content', exp_channel_data.`field_id_1` as 'page_seo_title' FROM (`exp_channel_titles`) JOIN `exp_channel_data` ON `exp_channel_titles`.`entry_id` = `exp_channel_data`.`entry_id` WHERE `exp_channel_data`.`channel_id` = 1 AND (`exp_channel_titles`.`entry_id` = 1 OR `exp_channel_titles`.`entry_id` = 2 OR `exp_channel_titles`.`entry_id` = 3 OR `exp_channel_titles`.`entry_id` = 4) ORDER BY `exp_channel_titles`.`channel_id` DESC

I know it's not a "where in" operator, but it does the same thing. Due to the way Channel Data parses this info, that' not currently possible without a decent re-write of code.
